// Copies the shared transcript module into the extension and the site.
//
// Neither a Chrome extension nor a Vercel project can load a file from outside
// its own folder, and this repository has no bundler. So the module is copied,
// and `--check` proves the copies still match the source.
//
// CommonJS, because it is build tooling for the root package, not shared code.

const { readFileSync, writeFileSync, mkdirSync } = require("node:fs");
const { dirname, join } = require("node:path");

const root = join(__dirname, "..");

const COPIES = [
  ["transcript-core/transcript.js", "extension/vendor/transcript.js"],
  ["transcript-core/transcript.js", "site/lib/transcript.js"],
  // The extension holds the source for this one, because it loads the file
  // directly and the site only copies it.
  ["extension/caption-view.js", "site/public/caption-view.js"],
];

const BANNER =
  "// GENERATED by `npm run sync` from transcript-core/. Do not edit.\n";

const check = process.argv.includes("--check");
let drifted = 0;

for (const [from, to] of COPIES) {
  const source = BANNER + readFileSync(join(root, from), "utf8");
  const target = join(root, to);

  if (check) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = "";
    }
    if (current !== source) {
      console.error(`drifted: ${to} does not match ${from}`);
      drifted += 1;
    }
    continue;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, source);
  console.log(`synced ${to}`);
}

if (check && drifted) {
  console.error("run `npm run sync` and commit the result");
  process.exit(1);
}
