// Copies the shared transcript module into the extension and the site.
//
// Neither a Chrome extension nor a Vercel project can load a file from outside
// its own folder, and this repository has no bundler. So the module is copied,
// and `--check` proves the copies still match the source.
//
// CommonJS, because it is build tooling for the root package, not shared code.

const { readFileSync, writeFileSync, mkdirSync } = require("node:fs");
const { dirname, join } = require("node:path");

const root = join(__dirname, "..");

const COPIES = [
  ["transcript-core/transcript.js", "site/lib/transcript.js"],
  // The extension holds the source for this one, because it loads the file
  // directly and the site only copies it.
  ["extension/caption-view.js", "site/public/caption-view.js"],
];

const BANNER =
  "// GENERATED by `npm run sync` from transcript-core/. Do not edit.\n";

// The content script cannot import ES modules, so it gets a classic-script
// build that wraps the same code and assigns one global.
//
// The fetch has to happen in the content script: it runs on youtube.com, so
// the call to YouTube's API is same-origin. The same call from a service
// worker carries `Origin: chrome-extension://<id>`, which YouTube answers 403.
const CLASSIC = {
  from: "transcript-core/transcript.js",
  to: "extension/vendor/transcript-classic.js",
  global: "TranscriptCore",
  exported: [
    "TranscriptError",
    "parseTimedText",
    "fetchTranscript",
    "createCache",
    "cutRange",
  ],
};

function toClassic(source) {
  const body = source.replace(/^export\s+/gm, "");
  return (
    `${BANNER}// Classic-script build for the content script. Do not edit.\n\n` +
    `const ${CLASSIC.global} = (() => {\n${body}\n` +
    `return { ${CLASSIC.exported.join(", ")} };\n})();\n`
  );
}

const check = process.argv.includes("--check");
let drifted = 0;

for (const [from, to] of COPIES) {
  const source = BANNER + readFileSync(join(root, from), "utf8");
  const target = join(root, to);

  if (check) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = "";
    }
    if (current !== source) {
      console.error(`drifted: ${to} does not match ${from}`);
      drifted += 1;
    }
    continue;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, source);
  console.log(`synced ${to}`);
}

{
  const source = toClassic(readFileSync(join(root, CLASSIC.from), "utf8"));
  const target = join(root, CLASSIC.to);
  if (check) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = "";
    }
    if (current !== source) {
      console.error(`drifted: ${CLASSIC.to} does not match ${CLASSIC.from}`);
      drifted += 1;
    }
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, source);
    console.log(`synced ${CLASSIC.to}`);
  }
}

if (check && drifted) {
  console.error("run `npm run sync` and commit the result");
  process.exit(1);
}
